import 'package:flutter/material.dart';

List<DropdownMenuItem<dynamic>> hobbies = [
  "Akvaryum bakımı",
  "Amatör radyo",
  "Araç restorasyonu",
  "Ağaç işleri",
  "Basketbol",
  "Baton çevirme",
  "Bilgisayar Programlama",
  "Bir evcil hayvanla oynamak",
  "Bisiklet sürmek",
  "Bonsai",
  "Boyama",
  "Dans",
  "Dağ bisikleti",
  "Dikiş",
  "Ev filmleri",
  "Ev otomasyonu",
  "Fotoğrafçılık",
  "Hava sporları",
  "Heykel",
  "Kano sporu",
  "Kaya tırmanışı",
  "Knapping",
  "Koşu yapmak",
  "Koşu",
  "Kumdan kale binası",
  "Kürek veya Kürek Çekme",
  "Locksport",
  "Motor sporları",
  "Müzik Enstrümanları",
  "Odyofili",
  "Pişirme",
  "Scrapbooking",
  "Serbest koşu",
  "Su Sporları",
  "Sörf yapmak",
  "Tahta sporları",
  "Tai chi chuan",
  "Takı yapımı",
  "Talaşlı imalat",
  "Taş",
  "Yaratıcı Yazarlık",
  "Yelken",
  "Yemek pişirme",
  "Yoga",
  "Yüzme",
  "parkur",
  "Çizim",
  "Örme",
  "Şarkı söyleme",
  "Şecere"
].map<DropdownMenuItem<String>>((String value) {
  return DropdownMenuItem<String>(
    value: value,
    child: Text(value),
  );
}).toList();
